# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/DELL/Desktop/Camera_Demo/.Xil/Vivado-1800-DESKTOP-8D0QN4O/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7s15ftgb196-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      D:/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog {
      C:/Users/DELL/Desktop/Camera_Demo/.Xil/Vivado-1800-DESKTOP-8D0QN4O/realtime/rgb2dvi_0_stub.v
      C:/Users/DELL/Desktop/Camera_Demo/.Xil/Vivado-1800-DESKTOP-8D0QN4O/realtime/csi_to_axis_0_stub.v
      C:/Users/DELL/Desktop/Camera_Demo/.Xil/Vivado-1800-DESKTOP-8D0QN4O/realtime/csi2_d_phy_rx_0_stub.v
      C:/Users/DELL/Desktop/Camera_Demo/.Xil/Vivado-1800-DESKTOP-8D0QN4O/realtime/AXIS_Data_RAM_stub.v
      C:/Users/DELL/Desktop/Camera_Demo/.Xil/Vivado-1800-DESKTOP-8D0QN4O/realtime/RAM_Line_stub.v
      C:/Users/DELL/Desktop/Camera_Demo/.Xil/Vivado-1800-DESKTOP-8D0QN4O/realtime/clk_wiz_0_stub.v
      C:/Users/DELL/Desktop/Camera_Demo/.Xil/Vivado-1800-DESKTOP-8D0QN4O/realtime/clk_wiz_1_stub.v
      C:/Users/DELL/Desktop/Camera_Demo/Camera_Demo.srcs/sources_1/new/Driver_Bayer_To_RGB.v
      C:/Users/DELL/Desktop/Camera_Demo/Camera_Demo.srcs/sources_1/new/Driver_Csi_To_Dvp.v
      C:/Users/DELL/Desktop/Camera_Demo/Camera_Demo.srcs/sources_1/new/Driver_IIC.v
      C:/Users/DELL/Desktop/Camera_Demo/Camera_Demo.srcs/sources_1/new/Driver_MIPI.v
      C:/Users/DELL/Desktop/Camera_Demo/Camera_Demo.srcs/sources_1/new/OV5647_Init.v
      C:/Users/DELL/Desktop/Camera_Demo/Camera_Demo.srcs/sources_1/new/Trigger_Generator.v
      C:/Users/DELL/Desktop/Camera_Demo/Camera_Demo.srcs/sources_1/new/digital.v
      C:/Users/DELL/Desktop/Camera_Demo/Camera_Demo.srcs/sources_1/new/digital_recognition.v
      C:/Users/DELL/Desktop/Camera_Demo/Camera_Demo.srcs/sources_1/new/gray.v
      C:/Users/DELL/Desktop/Camera_Demo/Camera_Demo.srcs/sources_1/new/posedge_detection.v
      C:/Users/DELL/Desktop/Camera_Demo/Camera_Demo.srcs/sources_1/new/rgb.v
      C:/Users/DELL/Desktop/Camera_Demo/Camera_Demo.srcs/sources_1/new/rgb_test.v
      C:/Users/DELL/Desktop/Camera_Demo/Camera_Demo.srcs/sources_1/new/shuzi.v
      C:/Users/DELL/Desktop/Camera_Demo/Camera_Demo.srcs/sources_1/new/Camera_Demo.v
    }
      rt::read_vhdl -lib xpm D:/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top Camera_Demo
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/DELL/Desktop/Camera_Demo/.Xil/Vivado-1800-DESKTOP-8D0QN4O/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
