# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# IP: ip/Picture_R_Rom_1/Picture_R_Rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Picture_R_Rom || ORIG_REF_NAME==Picture_R_Rom} -quiet] -quiet

# IP: ip/rgb2dvi_0/rgb2dvi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] -quiet
